### ISSUE TITLE
Coordinates format

### ISSUE THREAD

**Issue by flogsgit** [matyasbach/Mapy.cz-Wordpress-Plugin#4]
Hi, what format of coordinates should I use? Currently I get no map on the page. Thanks, Filip

**Comment by matyasbach** [comment]
Hi @flogsgit,
like this:
`Latitude: 13.371913, Longitude: 49.732509`
Do you need to support other formats?

**Comment by flogsgit** [comment]
So without letters NS WE because mapy.cz operates mainly in Czech Republic? :) No, this format is ok but there shlould be an example of this in the plugin. Thanks.

**Comment by matyasbach** [comment]
Mapy.cz used to work only for Czech Republic but now they work for whole world (using mostly OSM as a source I think).

I made a quick fix, now it supports all usual formats (like
13.3719131°W,
13°22'18.887" W,
13.37,
-13.37
etc.

Thanks for pointing this out :-)
